### PR TITLE
msgbox: workaround for n-call of PrepareMsgbox (fix #288)

### LINKED ISSUE #288: msgbox: calling init func two times causes unexpected behavior
to reproduce:
```golang
package main

import (
        "fmt"

        "github.com/AllenDang/giu"
)

func loop() {
        giu.Window("window").Layout(
                giu.PrepareMsgbox(),
                giu.PrepareMsgbox(),
                giu.Button("click me to see message box").OnClick(func() {
                        giu.Msgbox("Info", "I'm a msgbox. press OK to close me")
                }),
                giu.Button("show yes-no dialog").OnClick(func() {
                        giu.Msgbox("Question", "I'm yes-no dialog. Please take an action").
                                Buttons(giu.MsgboxButtonsYesNo).
                                ResultCallback(func(result giu.DialogResult) {
                                        switch result {
                                        case giu.DialogResultYes:
                                                fmt.Println("Yes clicked")
                                        case giu.DialogResultNo:
                                                fmt.Println("No clicked")
                                        }
                                })
                }),
                giu.Button("show ok-cancel dialog").OnClick(func() {
                        giu.Msgbox("ok-cancel", "I'm ok-cancel dialog").Buttons(giu.MsgboxButtonsOkCancel)
                }),
        )
}

func main() {
        wnd := giu.NewMasterWindow("Msg box demo", 640, 480, 0)
        wnd.Run(loop)
}
```

### PR DESCRIPTION
**Pull request by gucio321**

### CODE REVIEW

**Comment by AllenDang** [comment]
I'm thinking about to refine the whole concept of Popup. This is the most tricky part of imgui from my point of view. Mostly the rule 'popup could only be opened by the invoker who is defined at the same widget hierarchy'. It's very confusing. It makes me feels very hard to understand why popup doesn't work at the begining of learning imgui.

I have few thoughts here:
1. The popup should be defined at very certain position, rather than random layout in random widget hierarchy.
2. If two popups get same id, both of them should be opened, rather than merging their body.

**Comment by gucio321** [comment]
> The popup should be defined at very certain position, rather than random layout in random widget hierarchy.

what do you mean? what could the demo code look like?

> If two popups get same id, both of them should be opened, rather than merging their body.

sure, the other option is to disable such the solution - all popups should be its unique id - no duplicates else - `panic`

**Comment by AllenDang** [comment]
@gucio321 The popup should be defined at very certain position, rather than random layout in random widget hierarchy.
I mean, for example, we have a method in window widget named `Popups`, where is the only place to define popup.

**Comment by gucio321** [comment]
hmm, @AllenDang I just got an idea.
Maybe for now, change `PopupModal()` function name to `RegisterPopupModal`? Then, everyone'll know that this method doesn't actually make popup appear but just add it to the system?

**Comment by gucio321** [comment]
@AllenDang what should I do with this? close?

**Comment by AllenDang** [comment]
@gucio321 Let's leave it here as a reminder to refine Popup related code in future.

**Comment by gucio321** [comment]
closing, as #288 exists

**Pull request closed without merging**
