### PR TITLE
add AlignSetter

### PR DESCRIPTION
**Pull request by gucio321**
align setter is able to center/align to right some widgets.
it is some type of "BETA" solution and may contain lot of bugs

@AllenDang what do you think about this?

### CODE REVIEW

**Comment by AllenDang** [comment]
I tink this could be very useful at this point till https://github.com/ocornut/imgui/issues/3714 is fixed.

**Comment by gucio321** [comment]
well, after reading the imgui issue I chaned a bit applied solution

> There are methods that can be applied if you don't mind running logic twice. Out of the box I see two possible solutions:
>
>   - remember cursor position, draw a widget*, record size, move cursor back, draw widget again

so I'm rendering the invisible widgets at the position, they should be normally, getting thems positons and rendering them with alignment. It should be better, because in a previous solution, when source layout was changed, my ALignSetter got confused.

**Comment by gucio321** [comment]
## KNOWN BUGS
- all widgets will be build twice
it means, that if you have e.g. `CustomWidget` it could do unexpected things do. Example
```golang
giu.Align(giu.AlignToCenter).To(
   giu.Custom(func() { fmt.Println("running custom widget") }),
)
```
will print `running custom widget` 2 times per frame.

we may want to add some documentation (e.g. open issue for it)

**Comment by AllenDang** [comment]
@gucio321 add following to the comment of `Align` function is good enough for now.
```
// FIXME: all widgets will be build twice
// it means, that if you have e.g. CustomWidget it could do unexpected things do. Example
// giu.Align(giu.AlignToCenter).To(
//   giu.Custom(func() { fmt.Println("running custom widget") }),
// )
func Align(...)
```

**Comment by gucio321** [comment]
ok, it is done. I found the other bug btw (see [KNOWN BUGS](https://github.com/AllenDang/giu/pull/312#issuecomment-912969032)) I documented it in Align.go too.

**Pull request merged**
