### PR TITLE
Css widget

### LINKED ISSUE #463: suggestion: CSS styles
# INTRODUCTION

Hi there!
A few days ago, I heard, that JavaFX uses CSS stylesheets for windowed-apps styling.

What about adding such a feature as an extension of giu?

# technical aspect

at the moment, there is `setTheme` method that sets all styles in master window.
we can parse css file's body class and apply it there.
In addition, we can also add `CSSWidget` and use it e.g.:
```golang
CSSTag("mycustomstyle").To(/*some layout*/)
```
and during master window creation:
```golang
wnd := giu.NewMasterWindow(...)
err := wnd.StyleFromCSS([]byte(myStyle))
```

@AllenDang what do you think about this idea? could it be a part of giu? Or meybe it'd be better idea to write a separated module (like css-giu-widget (IMO it wouldn't be so simple to do, because of privacy of some in-giu stuff) ).

### PR DESCRIPTION
**Pull request by gucio321**
Hi @AllenDang !
I'm trying to fix #463

### CODE REVIEW

**Comment by gucio321** [comment]
@AllenDang it is mostly done, could you please give me your feedback on what do you think about this CSS Widget.
What is missing? is the syntax ok?

**Comment by gucio321** [comment]
Another question is: how to write Vector2 in CSS?
e.g.
```css
rule {
   window-rounding: Vec2(20, 40);
   window-rounding: {20, 40};
   window-rounding: 20, 40;
}
```

which one of the following looks the best? Or should I implement all of them?

**Comment by gucio321** [comment]
ugh, it seems that go-css is bugged and cannot parse multiple rules...
converting back to draft

**Comment by gucio321** [comment]
okey, conflicts fixed @AllenDang

**Comment by gucio321** [comment]
well, getting back here.
FYI, I find this widget really useful. E.g. i projects with more than one contributor, the people who are not familiar with go, can work on styles easily. [e.g. here is my project using CSSWidget](https://github.com/TheGreaterHeptavirate/constitutor)

There two more things to be done here:
- [ ] go-css is now fixed, so I'd preffer to use upstream
- [ ] there is still no support for vec2 values

**Comment by gucio321** [comment]
well, @AllenDang it is also ready to merge now

**Comment by AllenDang** [comment]
@gucio321 I think we need to provide a list of supported css styles somewhere, maybe in the header comment of css.go?

**Comment by gucio321** [comment]
ok @AllenDang  it is in `docs/css.go`

**Comment by gucio321** [comment]
wooow, this has already 5 months :smile:

**Pull request merged**
