### PR TITLE
Update imgui to 1.79

### PR DESCRIPTION
**Pull request by zlianon**

### CODE REVIEW

**Comment by AllenDang** [comment]
Thanks very much for your effort.
But those two functions and related code need to remain to implement power saving mode which could decrease the CPU usage when user doesn't interact with ui.
```
SetMaxWaitBeforeNextFrame
GetFrameCountSinceLastInput
```

**Comment by zlianon** [comment]
I think it's good now

**Comment by zlianon** [comment]
@AllenDang i think it's good now

**Comment by SpaiR** [comment]
@AllenDang Copy-pasting the latest Dear ImGui .h/.cpp files is a kind of way to up the version. Yet, the PR missed the point of such updates. Take a look at the diff between two versions https://github.com/ocornut/imgui/compare/v1.76...v1.79 , specifically `imgui.h` file (which reprsents a public API to use). There are a ton of changes and they should be manually ported. Otherwise sooner or later you'll just break a compatibility with the original library and API itself.

**Comment by AllenDang** [comment]
@SpaiR Yes, this is a potential issue. And I need to spend more time to review the changes. Currently I just read the change log and guess where might need to be changed. Do you know any better way to follow the changes from up stream?

**Comment by SpaiR** [comment]
In a couple of days I will do a PR to the intial [imgui-go](https://github.com/inkyblackness/imgui-go) binding with compatible update to v1.79. I'm not sure how soon it will be merged, but you could use it as reference for your local copy. I can CC you there.

I would also recommend to consider to get rid of storing the local version of the binding and use the noted one. That will be much efficient from the point of opensource development and golang community in general.

**Comment by AllenDang** [comment]
@SpaiR The reason of local copy is I used a un-merged PR of imgui for Power-saving feature. Therefore I have to add those parts to imgui.h and imgui_internal.h manually each time.

**Comment by SpaiR** [comment]
I see. Well, I may be wrong, but I've checked the code from the commit [`70e5cdf` (#81)](https://github.com/AllenDang/giu/pull/81/commits/70e5cdff5b384dc0a59685cb0315a25b9e2a6a46) and it seems for me that it could be implemented fully on the application side. Basically, it catches input events from user (which is already done in the platform) and waits if nothing has happened. I don't see why it should be on Dear ImGui side. Yet, it's all just suggestions and I don't insist on aything.

Speacking about version update. The only way in situation with local version is to port everything manually...

**Comment by AllenDang** [comment]
@SpaiR You may right. I will check that. If we could implement it on app side that will be great.

**Pull request merged**
