### PR TITLE
widgets: add formatting possibility to some widgets

### PR DESCRIPTION
**Pull request by gucio321**
hi there,
it may be useful to do just
`giu.Label("this is some int: %d and string %s", 5, "string")`
instead of using fmt.sprintf
`giu.Label(fmt.Sprintf("this is some int: %d and string %s", 5, "string"))`
or maybe I should add `Labelf`?

### CODE REVIEW

**Comment by AllenDang** [comment]
1. For 'Format' method, the format string is handled by c++, I don't suggest to format at first in go side.
2. To add a new parameter named 'args' will confuse user, unless they read the document which we don't have, then more confuse. For this kind of operation, I suggest we keep them out of library, to keep the simplicity of API.

**Comment by gucio321** [comment]
okey, @AllenDang what about
```golang
func Labelf(format, string, args ...interface{})*Label{
     return Label(fmt.Sprintf(fomrmat,args...)
}
```

**Comment by AllenDang** [comment]
> okey, @AllenDang what about
> 
> ```go
> func Labelf(format, string, args ...interface{})*Label{
>      return Label(fmt.Sprintf(fomrmat,args...)
> }
> ```
> 
> it wouldn't be so confusing

This would be good! :P

**Comment by gucio321** [comment]
@AllenDang what about `(*SliderInt).Formatf` is it ok?

**Comment by AllenDang** [comment]
@gucio321 For existing 'Format' method, I need to refact them to use go's format instead. Let's add format to label first. After that I will follow your pattern to deal with 'Format'.

**Comment by gucio321** [comment]
@AllenDang it is done

**Pull request merged**
