### PR TITLE
Complete missing docs

### PR DESCRIPTION
**Pull request by gucio321**
make progress on #41 

# TODO
- [x] Alignment.go (fc35147)
- [x] ClickableWidgets.go (87a008b)
- [x] CodeEditor.go (666eae9)
- [x] Context.go (a6d0531)
- [x] Direction.go
- [x] doc.go
- [x] EventHandler.go
- [x] Events.go (d830a32)
- [x] Flags.go (2f44f8b and other)
- [x] FontAtlasProsessor.go (no fixes in this pr)
- [x] ImageWidgets.go (11c3dd7)
- [x] InputHandler.go (3b367e3) 
- [x] Keycode.go
- [x] Layout.go
- [x] ListClipper.go (c0593eb)
- [x] MasterWindow.go (9e30519)
- [x] Msgbox.go
- [x] Popups.go (b3b6e69)
- [x] SliderWidgets.go (3316c6e)
- [x] SplitLayout.go (966d080)
- [x] StackWidget.go (372c886 )
- [x] Style.go (3117c48)
- [x] TextureFilters.go
- [x] Texture.go (7c1787b)
- [x] TextWidgets.go (dab7c53)
- [x] Utils.go (6ce7503)
- [x] Window.go (61b9890 )
- [ ] Canvas.go
- [ ] ExtraWidgets.go
- [ ] Plot.go
- [ ] ProgressIndicator.go
- [ ] TableWidgets.go
- [ ] Widgets.go
- [x] Context_test.go (nothing here)
- [x] InputHandler_test.go (noop)

### CODE REVIEW

**Comment by gucio321** [comment]
@AllenDang what is a difference between Popup and PopupModal?
what comments should I put over them?

**Comment by gucio321** [comment]
btw, I'll sort the widgets as follows:
- type deffinition (e.g. type ButtonWidget {...})
- constructor(s) ( `func Button(...) {...}`, `func Buttonf(...) {...})`)
- setters (`func (b *ButtonWIdget) OnClick(...) *ButtonWIdget {...}`)
- Builder (`func (b *ButtonWIdget) Build() {...}`)

**Comment by gucio321** [comment]
> @AllenDang what is a difference between Popup and PopupModal?
what comments should I put over them?

oh, got it

**Comment by AllenDang** [comment]
@gucio321 Popup won't block user input which PopupModel will.

**Comment by AllenDang** [comment]
@gucio321 I can't say enough thank you, man, this is a lot, thank you from the bottom of my heart!

**Pull request merged**
