### PR TITLE
Implement min/mag texture filtering

### PR DESCRIPTION
**Pull request by kettek**
These changes allow users to call SetTextureMinFilter and SetTextureMagFilter on the MasterWindow to change how textures are
filtered for rendering. This allows pixel-perfect rendering via giu.TextureFilterNearest.

### CODE REVIEW

**Comment by AllenDang** [comment]
@kettek I think those two functions should be added to renderer interface only. Because they are kind of rarely be used, which could remain the simplicity of MainWindow structure.
So the usage could be like this
```go
func main() {
  wnd := g.NewMasterWindow(...)
  g.Context.GetRenderer(). SetTextureMinFilter(...)
  g.Context.GetRenderer(). SetTextureMagFilter(...)
  ...
}
```
Do you think this is doable?

**Comment by kettek** [comment]
That would certainly be simpler and would be functionally equivalent -- I'll make adjustments.

**Comment by kettek** [comment]
Now adjusted to remove MasterWindow methods.

**Comment by AllenDang** [comment]
@kettek Thanks! Can you add a demo about how to use those two functions?

**Comment by kettek** [comment]
I've created an example in `examples/texturefiltering`. One problem I noticed is that sometimes the program will freeze. I think this is due to a race condition stemming from the goroutine for creating the image textures -- giu is accessing the texture variables before they are guaranteed to be populated with the actual texture data. Unfortunately using channels didn't solve the problem (it just froze it entirely... which is strange).

I left commented out in the code additional buttons for setting some other mipmap modes -- I have disabled them since their use causes non-image imgui draw calls to not be rendered.

**Comment by kettek** [comment]
To note, I think this is related to #30

**Comment by AllenDang** [comment]
I tried to solve this once, and I did fix it with giu, but unfortunately the upstream lib GLFW also has same problem. I need to create a PR to GLFW when I got time.

**Pull request merged**
