### PR TITLE
Add advanced image usage tools with examples

### PR DESCRIPTION
**Pull request by cjbrigato**
Adds ReflectiveBoundTexture and Stateful abstraction Adds SurfaceLoaders to go with
Show usage of such new objects with examples:
* loadimageAdvanced mimics loadimage but with new objects
* asyncImage shows usage of states and events
* paint is full featured paint with drawCommands and undo buffer for minimal footprint. Perfect for usage over socket and collaboration

Note: paint use embed.fs so you can just do `go run github.com/AllenDang/giu/examples/paint@latest` once it's merged :)

[paintexample(1).webm](https://github.com/user-attachments/assets/9bcf73f6-de93-4f37-a601-a6da63a8211f)

### CODE REVIEW

**Comment by cjbrigato** [comment]
@gucio321 it passes linter.

Could you review again. This has  been so much time and line since it started.

**Comment by cjbrigato** [comment]
(rebased on upstream master)

**Review by gucio321 — APPROVED** [review]
lgtm, Paint is awesome :tada:

**Comment by cjbrigato** [comment]
if you like paint, you'll like the incoming version with "collaborative realtime paint" over giu :p (hence the "Drawcommands" and buffers: it's made for sending and receiving states over sockets 🗡️ )

**Pull request merged**
