### PR TITLE
master window: add Close method

### PR DESCRIPTION
**Pull request by gucio321**
reffers to #264. (*MasterWindow).Close() closes the master window and allows to execute further code.
@allenDang you need to merge https://github.com/AllenDang/imgui-go/pull/8 before this one could be ready.

### CODE REVIEW

**Comment by AllenDang** [comment]
@gucio321 Done, upstream is merged.

**Comment by gucio321** [comment]
okey, @allenDang it works for now

**Comment by AllenDang** [comment]
@gucio321 Got another conflict here.

**Comment by gucio321** [comment]
it is done

**Pull request merged**
