### PR TITLE
github/workflows: add golangci-lint workflow

### PR DESCRIPTION
**Pull request by gucio321**
hi, here is a golangci-lint action suggested in https://github.com/AllenDang/giu/pull/323#issuecomment-916579864
but first, @AllenDang could you push some `.golangci.yml` config file.(https://golangci-lint.run/usage/configuration/)

### CODE REVIEW

**Comment by AllenDang** [comment]
@gucio321 Do you mean I need to push a default .golangci.yml at first?

**Comment by gucio321** [comment]
> @gucio321 Do you mean I need to push a default .golangci.yml at first?

you need to push golangci-lint config, you're using / you'd preffer to use in giu, because my workflow seems doesn't working without it

**Comment by AllenDang** [comment]
@gucio321 It's done.

**Comment by gucio321** [comment]
well, I'll try to make this workflow running

**Comment by gucio321** [comment]
well, linter workflow works now. we just need to fix a tone of lint errors :grinning:

**Pull request merged**
