### PR TITLE
go mod: update to go 1.18

### PR DESCRIPTION
**Pull request by gucio321**
@AllenDang go 1.18 is there!
here is changelog: https://go.dev/doc/go1.18
that new feature - generics - seems to be interessting. I need to investigate it as I don't understand how does it work yet.

### CODE REVIEW

**Comment by AllenDang** [comment]
@gucio321 Homebrew doesn't update golang to 1.18 yet, I may need more time to get my hand on it.

**Comment by gucio321** [comment]
yah, i know that issue, since go 1.16 I'm not using package manager's version of golang anymore
I download it directly from golang's website and unpacking into my system
on linux there is just a few lines of commands
```sh
wget https://go.dev/dl/go1.18.linux-amd64.tar.gz
sudo su -
cd /usr/local
rm -rf go
tar xvf /home/me/go1.18.linux-amd64.tar.gz
```
idk how would the paths look for mac but that sheme probably could be applied too

**Comment by AllenDang** [comment]
Ok, I got 1.18, trying now.

**Comment by AllenDang** [comment]
@gucio321 There is a confliction, can you resolve it?

**Comment by gucio321** [comment]
@AllenDang it is done!

**Comment by gucio321** [comment]
hmm, wait a while, I'lll update linter as it fails now...

**Comment by gucio321** [comment]
well it works now

**Pull request merged**
