### PR TITLE
Input manager

### PR DESCRIPTION
**Pull request by gucio321**
Hi,
It could be nice to support keyboard shortcuts inside of giu.

### CODE REVIEW

**Comment by gucio321** [comment]
https://user-images.githubusercontent.com/73652197/122369461-80d12e00-cf5e-11eb-9fc1-d8d7002285a5.mp4

**Comment by AllenDang** [comment]
First thing comes to my mind is to use RegisterShortcuts(shortcuts ...giu.WindowShortcut) instead to simplify code writing.

**Comment by gucio321** [comment]
@AllenDang you can use it anyway, however for local shortcuts it makes more sense to register them with window

**Comment by gucio321** [comment]
> First thing comes to my mind is using RegisterShortcuts(shortcuts ...giu.WindowShortcut) to simplify code writing.
oh, you mean for master window?

**Comment by AllenDang** [comment]
@gucio321 I mean both, you've already made the changes.

**Comment by gucio321** [comment]
@AllenDang could you merge PR on imgui-go, then I'll marke this as ready for review.

**Comment by AllenDang** [comment]
@gucio321 Sure, it's done.

**Comment by gucio321** [comment]
ok @AllenDang now it should work for everyone, not only me with hacked imgui-go version :grinning:

**Comment by AllenDang** [comment]
@gucio321 It has conflict after merged bring to front pr.

**Comment by gucio321** [comment]
@AllenDang done

**Pull request merged**
