### PR TITLE
CI: Remove codecov

### PR DESCRIPTION
**Pull request by asmaloney**
There are no tests to run, so it's just noise in the PRs.

(Based on discussion in #613.)

### CODE REVIEW

**Comment by gucio321** [comment]
maybe just disable the PR comments?
This will break badge in readme...

**Comment by asmaloney** [comment]
But if it isn't running any tests, why is it even running at all?

(Removed badge in README.)

**Comment by gucio321** [comment]
but there is a few tests, it is just ~2% :smile:

**Comment by asmaloney** [comment]
OK 😆 

I don't see any point in running codecov for this project since (1) it's not the type of project where you can get high code coverage (2) it's just noise in PRs, and (3) it just wastes resources & takes extra time for no benefit at all.

I guess you/@AllenDang can just close this PR if you/he want to keep codecov around for some reason!

**Comment by gucio321** [comment]
> I guess you/@AllenDang can just close this PR if you/he want to keep codecov around for some reason!

sadly, I don't have such a power :smile:
we need to let @AllenDang to decide here ;-)

**Pull request merged**
